Feature home page
okikiola11/html-forms pull request #3
Opened 2020-02-24 15:46 UTC by okikiola11

#### What does this PR do?
- Shows how to create HTML Forms

#### Description of Task to be completed?
- Added the header tag
- Added the main section tag which contains the various input boxes and elements.
- Added the footer.
- Ran validations on our Html and CSS.

#### How should this be manually tested?
- Clone this branch.
- open the index.html file on your browser

#### Screenshot
![screenshot]
![screenshot](https://user-images.githubusercontent.com/40399370/75166963-f5a6a600-5724-11ea-851e-34c54cee62f6.PNG)

2020-02-24 18:03 UTC, pelzolga123 requested changes
Project requires changes.

2020-02-24 18:03 UTC, pelzolga123 commented
## Hi Team! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
### Your project looks :+1: amazing!
### Kudos for great descriptive Pull Request :1st_place_medal: 
* [ ] check HTML markup with this [validator](https://validator.w3.org/#validate_by_upload). Now it shows one error in your project.
* [ ] stickler is present but not setup correctly, so not checking your project yet. Take a look [here](https://github.com/microverseinc/linters-config/tree/master/css) to configure your stickler. Right now it doesn't have the right content.
* [ ] Images are not displaying correctly right now. Row under intuit logo should contain Mint logo and text, Quickbooks logo an text,  Turbotax logo and text  (logo on the left, text on the right) ([link to page](https://accounts.intuit.com/signup.html))
![image](https://user-images.githubusercontent.com/20416431/75178039-f26ce380-573f-11ea-9c1f-2a71686a2b03.png)

* [ ] Phone `<input>` should be of type `tel` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/html_forms/form_and_input_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59524927/))
* [ ] Your form is missing a disclaimer text that matches the context and style of the original page ([link to page](https://accounts.intuit.com/signup.html))
![image](https://user-images.githubusercontent.com/20416431/75178167-41b31400-5740-11ea-8839-22b10e868019.png)

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2020-02-25 11:37 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @okikiola11 and @frankopkusianwar :balloon:  :lollipop: 

### Thank you for doing the changes required by the previous reviewer Good job! :medal_sports:  your project looks almost like the original :microscope: 

### you just have to make a couple more changes and some optional ones if you'd like :point_down: 

## Follow up

**Broken images**

- [ ] The images are still broken on your page, change the extensions from `.png` to `.PNG` I have commented your code where changes have to be made :arrow_double_down: 

- this is how it looks in the inspector with the change:

![image](https://user-images.githubusercontent.com/52209067/75243070-d9d7ea00-578e-11ea-8f34-eaed68eff542.png)

**Page structure**

- [ ] The order of the words in the original page is: **turbotax**, **quickbox** and **mint** and yours is **mint**, **quickbooks** and **turbotax**, the logos are in the right position so let's rearrange the words:

- Yours

![image](https://user-images.githubusercontent.com/52209067/75243358-5bc81300-578f-11ea-94d0-e9c62b8b14d2.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/75243396-70a4a680-578f-11ea-8fad-27879949753e.png)

## Optional

- [ ] [OPTIONAL]your Live Demo leads to a not found page, fix it or remove it from your Readme file
- [ ] [OPTIONAL] I encourage the use of  the `<nav>` tag for the major navigation links

### That's it team! :raised_hands: 

### Please :pray:  do the changes :memo: and submit back for a code review when you are done :rocket: 

Happy coding! :woman_technologist: 

Any questions? ask me on slack **@ Maru**

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

2020-02-25 11:37 UTC, euqueme commented on index.html
> +                <img src="assets/images/logo.png" alt="Company Logo"/>
change `src="assets/images/logo.png"` to: 

- `src="assets/images/logo.PNG"`

2020-02-25 11:37 UTC, euqueme commented on index.html
> +                    <img src="assets/images/icon-1.png" alt="Mint Icon"/>
change `src="assets/images/icon-1.png"` to:

- `src="assets/images/icon-1.PNG"`

2020-02-25 11:37 UTC, euqueme commented on index.html
> +                    <img src="assets/images/icon-2.png" alt="Quickbook Icon"/>
change `src="assets/images/icon-2.png"` to:

- `src="assets/images/icon-2.PNG"`

2020-02-25 11:37 UTC, euqueme commented on index.html
> +                    <img src="assets/images/icon-3.png" alt="Turbotax Icon"/>
change `src="assets/images/icon-3.png"` to:

- src="assets/images/icon-3.PNG"

2020-02-25 12:32 UTC, rOluochKe approved these changes
Hello Team
### Good job so far and making the review changes :clap: and your project looks good. Congratulations :boom: :100: I approve of this project.
### You can merge and submit a project completion form from your dashboard. Good luck with the next project.
- Happy coding!

2020-02-25 12:52 UTC, merged